# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drone.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64rone.proto\x12\x05\x64rone\"1\n\x03ROI\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01w\x18\x03 \x01(\x05\x12\t\n\x01h\x18\x04 \x01(\x05\"\x17\n\x08KeyEvent\x12\x0b\n\x03key\x18\x01 \x01(\t\"O\n\x07\x43ontrol\x12\x19\n\x03roi\x18\x01 \x01(\x0b\x32\n.drone.ROIH\x00\x12\x1e\n\x03key\x18\x02 \x01(\x0b\x32\x0f.drone.KeyEventH\x00\x42\t\n\x07\x63ontrol\"2\n\x05\x46rame\x12\x0b\n\x03jpg\x18\x01 \x01(\x0c\x12\x0c\n\x04hint\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t2>\n\x0b\x44roneStream\x12/\n\x0bStreamVideo\x12\x0e.drone.Control\x1a\x0c.drone.Frame(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROI']._serialized_start=22
  _globals['_ROI']._serialized_end=71
  _globals['_KEYEVENT']._serialized_start=73
  _globals['_KEYEVENT']._serialized_end=96
  _globals['_CONTROL']._serialized_start=98
  _globals['_CONTROL']._serialized_end=177
  _globals['_FRAME']._serialized_start=179
  _globals['_FRAME']._serialized_end=229
  _globals['_DRONESTREAM']._serialized_start=231
  _globals['_DRONESTREAM']._serialized_end=293
# @@protoc_insertion_point(module_scope)
